### ISSUE TITLE
Save user's comments to database.

### ISSUE THREAD

**Issue by YUBILAND** [cse442-at-ub/project_s23-cinco#100]
Acceptance Test 1:
1. Go to build https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build
2. Click on a post and press the add comment button that looks like this
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/4dc836b3-a3c7-4eb3-b29d-28c812ccf4b3)
3. Make sure you are redirected to the login page if you are not signed in.

Acceptance Test 2:
1. Login using david123 and pass Qwerty!234
2. Click on any post in the feed area
3. Click the comment icon
4. Verify the Post button below the comment text field is greyed out and is not clickable ( this is because the comments field is currently empty)
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/c7c5bad6-c3f9-470d-bf5b-769f122ea04f)
5. Type anything in the text field and verify the button turns yellow and is clickable (which will post whatever comment you inputted)
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/1a8b7531-a043-4f3a-ae0f-122bf98a12ba)

Acceptance Test 3: 
1. Type anything you would like in the comment field
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/a28d6dde-3594-4bb5-9719-a7b265b552b0)
2. Click submit and the field should then close and you can see the comments section again.
3. Scroll down until you can see your comment
4. Verify you can see your username, profile picture, comment, and post date.
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/8ec64199-1fb6-4de1-bac1-1c7dea1f7612)

Acceptance Test 4:
1. Type in a comment with html code such as "<h1><u> wait zenhub doesn't escape html? interesting</u></h1> , the comment should look like this &lt;h1&gt;text here&lt;/h1&gt;
2. Post the comment
3. Scroll down and verify that the html is escaped when displayed in the comments section observing no visual change of the comment such as larger text size or different font.
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/b5143643-993d-4865-8587-c1d82c6ccd5a)

Acceptance Test 5:
1. At any time please try exiting the event popup by clicking anywhere in the greyed-out feed area background.
2. Try exiting using the X button on the top right to close out of the event popup.
3. Finally try closing the comment popup by clicking on the comment button again.

Task Test:
1. Navigate to the database->comments, verify you can see your comment.
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/0c87e2f8-d425-4322-9d20-d587b4b18bae)

**Comment by junqiwu02** [comment]
Add a test for closing the comment prompt (by clicking the comment button again) without posting

**Comment by junqiwu02** [comment]
Add a test for testing html injection. For example if you try to enter <h1>Hi</h1> it should show up as plain text

**Comment by junqiwu02** [comment]
add a test for the logged out version

**Comment by YUBILAND** [comment]
Added test for closing comment popup by clicking comment button again. (Acceptance Test 5)
Added test for html injection. (Acceptance Test 4)
Added test for commenting when logged out. (Acceptance Test 1)
