### ISSUE TITLE
Create a database connection with the static badges page which was integrated with main application

### ISSUE THREAD

**Issue by vikasithsai** [cse442-at-ub/project_s23-cinco#105]
Task Test

Test 1:
Run the tests in dev branch
Enter the command " https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/ "
Functionality taken from static page carried the data from the database.

 If the user is logged out then user cannot able to view the badges
![CCA7ECF5-4D07-4DE2-8423-E31BB2A188E4.jpeg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/e8c7d3dd-ea9a-43f5-a48e-6336a3fbd2dc)
If the user logged in then user can view the badges
Verify the page looks like the screenshots
Both Versions are given below 
Desktop Version in Pic 1
Mobile Version in Pic 2

Click on badges
Badges History and Number of Badges in event categories integrated with the event management page

Desktop Version: 

![3BD70C5D-4D06-47E5-AE78-A5ACF516E98B.jpeg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/5b94eed1-1aa7-4e99-b87f-b9532381eabe)

Mobile Version:
![2774FD5F-D62E-42D8-8E24-DDA0599A61A6_1_201_a.jpeg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/739fdb27-e199-4034-8357-3391334a9252)

Test 2:
Suppose user attended an event 

![8CC60951-498E-4937-8BDB-7E4772199BF7.jpeg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/80cbbd47-5c54-4743-9033-677a750a0243)

User attendance can recorded and updated in badges page in category wise

![01CCF9ED-E227-4292-B432-59E9A887863E.jpeg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/125e6d64-64a9-4d15-a90c-76f6d7315b7e)

**Comment by junqiwu02** [comment]
Change this to block #98 instead since #104 is a duplicate

**Comment by junqiwu02** [comment]
Add a test to show that it dynamically updates based on the user data. For example, have a test to enter an event code and show that the number of events on this page goes up by 1.

**Comment by junqiwu02** [comment]
Also add a test for if the user is logged-out
