### ISSUE TITLE
Implement prepared statements in profile/settings php files

### ISSUE THREAD

**Issue by johntolo** [cse442-at-ub/project_s23-cinco#108]
Test 1: 
Go to edit-profile.php, edit-settings.php, loadSettings.php, and loadAccSettings.php and ensure that prepared statements are now in the files
Go to website url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
Log in with username: host12, password: Ubcse123.
Go to Profile and ensure that info is autofilled as it should be. See screenshot
Update the name to be Jonathan, click save, and ensure that it updates that field as it should be. see screenshot.

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/3cb5dc37-3657-4ea7-b6d3-a2fe51f5e637)
![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/81cfc90f-da19-42b0-a50e-c94fea03df4f)

Test 2: 
Do the same steps as Test 1 except test the Account Settings instead

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/dc379d79-d14d-4f54-9772-ee1e40e1152f)
![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/90eef097-6dbb-41e2-aa6a-6e00b075e5d8)

Test 3:
Go to website url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
Log in with username: host12, password: Ubcse123.
Go to Account Settings and in the "First Name" field, type '; DROP TABLE Account Settings;--
Go to account settings database and ensure that the injection did not delete the whole table

**Comment by junqiwu02** [comment]
Add a test for sql injection. try changing the username to '; DROP TABLE;--

**Comment by junqiwu02** [comment]
no sure if that's the right injection, ensure whatever you use is an actual injection test
