### ISSUE TITLE
Add all links to mobile slideout menu

### ISSUE THREAD

**Issue by johntolo** [cse442-at-ub/project_s23-cinco#112]
Test 1:
Go to website url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
Log in using any credentials
Right click and click inspect to see mobile view
Ensure that all the tabs on normal view are now visible in slideout menu (see screenshot)
Go to every link in slideout menu and ensure it takes you to its respective page

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/0f94f3f8-732e-4087-9fc4-f7e74ad2fdbb)

**Comment by junqiwu02** [comment]
Rephrase "works as intended" to "the buttons redirect you to their respective page"
