### ISSUE TITLE
Make user profile pictures seen in feed, event view, and comments

### ISSUE THREAD

**Issue by tyland5** [cse442-at-ub/project_s23-cinco#117]
**Task Tests**

*Test 1*
1) https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2) See if profile pictures are shown next to the names of the posters in the feed view.
3) Click on an event and see if the poster's profile picture is shown 
4) See if the comments have profile pictures with them if applicable.
Results will look like this:![Screenshot (1151).png](https://images.zenhubusercontent.com/63e2cfbfaca3b22752e618ee/86d89790-d184-46b1-943e-6ac89011728e)

**Comment by junqiwu02** [comment]
needs a dependency
