### ISSUE TITLE
design landing page on Figma 

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#12]
*Task Tests*

test 1:
-go to figma page: https://www.figma.com/proto/5qJUyXFUAdbtiobIQYqH20/Project-Prototype?node-id=51%3A153&scaling=scale-down&page-id=0%3A1
- check for the login/sign up button on top right of screen.
- look for the filter button on top right of screen
- check the navigation bar on top left of screen
- see the current events posted (UB hackathon for all of them)
- look for the bookmark button, in the shape of a star, next to each title of the event.

test 2:
- click on login button on top right
- ensure that it opens the login page

**Comment by junqiwu02** [comment]
Add a link to the Figma in the tests!
