### ISSUE TITLE
Create Navbar home keys hover to like they are functioning 

### ISSUE THREAD

**Issue by vikasithsai** [cse442-at-ub/project_s23-cinco#122]
Task Test

Test 1:
Click on the link  " https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/ " To test the hovering of navbar and slideout menu

Please verify the screenshots below

![98F0319E-2365-421A-849E-EB9EBA0DD948.jpeg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/f13d2071-c5db-450f-aae1-f7b2ddfe393c)

![9DDC2D97-15E2-4D47-93B9-5857A62CE322.jpeg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/e90fa0a9-793c-4063-bd96-8b91dd75d318)

**Comment by junqiwu02** [comment]
there's no test
