### ISSUE TITLE
As a new browser, I want to enter the website so I can immediately see what events are up

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#13]
**Acceptance Tests**

test 1:
- enter the website url: https://www.figma.com/proto/5qJUyXFUAdbtiobIQYqH20/Project-Prototype?node-id=151%3A3&scaling=scale-down&page-id=151%3A2&starting-point-node-id=151%3A3
- scroll down to see events posted![scroll-to-see-events.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/d4eb9f0c-a72f-4cd2-ad91-8082a16d0c7d)

**Comment by junqiwu02** [comment]
The tests need to be more specific. What URL am I entering? What does the posted events look like? (A screenshot will help for the second one).
A tip for stories specifically to avoid rewriting tests, you can have the test be to run the task test in task X, Y, Z, etc.

**Comment by junqiwu02** [comment]
Also stories should not have a task label

**Comment by junqiwu02** [comment]
Add an assignee
