### ISSUE TITLE
Design log in screen on Figma

### ISSUE THREAD

**Issue by johntolo** [cse442-at-ub/project_s23-cinco#14]
Go to website login page: https://www.figma.com/file/8pMMrECO2YUx86OFXKaJLl/Untitled?t=NLfh2fBFdCM1SvqR-0

Test 1:
Check that there is a text field for username and password.
Check that there is a login button.
Check for a "forgot password" option and its button.
Check for a sign up or register option and its button.

Test 2:
Ensure that the login button takes you to the homepage of the website if successful, and won't if not successful.
Ensure that the forgot password button will take you to a screen that will help you change your password.
Ensure that the register button will take you to a screen where you can sign up for the website.

**Comment by junqiwu02** [comment]
Add a link to the figma in the tests!

**Comment by junqiwu02** [comment]
Add this task as a dependency of a user story and add an assignee as well.
