### ISSUE TITLE
As a member of the website, I want to login using my credentials so I can see I am logged in

### ISSUE THREAD

**Issue by johntolo** [cse442-at-ub/project_s23-cinco#17]
Go to login screen

Test 1:
Go to website: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build
Click login and login with credentials
See that you are now at the home page and logged in (see screenshot)

Test 1:
Go to website: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build
Click login and enter in wrong username or password
See that the login was unsuccessful and doesn't bring you to homepage (see screenshot)

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/cffca461-5d5d-48f6-ab01-177ff973faa2)

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/e0166007-9b22-4bc8-88d5-cc4bd905535a)

**Comment by junqiwu02** [comment]
Add sprint labels

**Comment by junqiwu02** [comment]
add some screenshots to the tests

**Comment by junqiwu02** [comment]
add the cheshire link
