### ISSUE TITLE
Create static homepage for mobile users and have it be hosted on the UB Cheshire server

### ISSUE THREAD

**Issue by tyland5** [cse442-at-ub/project_s23-cinco#18]
**Task Tests**

Test 1:
1) Go to the url of the actual site: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2) Inspect elements and look how the website looks in almost every mobile viewport
3) Ensure that the feed looks nearly identical to the Figma prototype

**Comment by tyland5** [comment]
Currently checking on Bootstrap and also seeing if we were to use React, how would we deploy it and such

**Comment by tyland5** [comment]
Made somewhat of a responsive nav bar for webpage. Currently figuring out how to properly create branches for github

**Comment by junqiwu02** [comment]
I think the diverging branches might only show up on the graph once both branches start having changes or if the second branch is merged back into the first. I may be wrong though

**Comment by junqiwu02** [comment]
You can get rid of "push to GitHub" from the title. It is an expected part of every code task.
