### ISSUE TITLE
As a member of the website, I want to be immediately taken to the feed after logging on so I can look right away at what events are nearby

### ISSUE THREAD

**Issue by tyland5** [cse442-at-ub/project_s23-cinco#19]
**Acceptance Tests**

*Test 1* 
Desktop view
1) Open this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2) Check if you can see the feed after clicking on the link. You should be able to see posts. They should be arranged in columns of 2-4 depending on your screen size like this:
![Screenshot (57).png](https://images.zenhubusercontent.com/63e2cfbfaca3b22752e618ee/920f1096-3d1a-4564-a56f-e361c3da011b)

*Test 2*
Mobile view
1) Open this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2) Check if you can see the feed after clicking on the link. You should be able to see posts. They should be arranged in 1 column depending on your screen size like this:
![Screenshot (59).png](https://images.zenhubusercontent.com/63e2cfbfaca3b22752e618ee/8e25d674-db57-48fc-8a13-b643b1ff266c)

**Comment by junqiwu02** [comment]
Add an assignee

**Comment by junqiwu02** [comment]
The description of the feed and posts in test 1 needs to be more detailed so that a tester can clearly assert if it's the correct feed. A detailed description or a screenshot would suffice. Also please separate the test into a test each for mobile and desktop versions.
