### ISSUE TITLE
Create a description screen in figma which displays when the user clicks on a post.

### ISSUE THREAD

**Issue by YUBILAND** [cse442-at-ub/project_s23-cinco#21]
Visual Test

1. Go to the figma page: 
https://www.figma.com/file/5qJUyXFUAdbtiobIQYqH20/Project-Prototype?node-id=151%3A3&t=ZUp55reD6yzeYedK-0
2. Click on the frame that says Description.
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/c5f79bb7-e08d-49eb-89ef-c4fe6e4fbef1)
3. Confirm the frame shows up providing new visual information such as the event description, RSVP, likes, comments section, the location, and the profile of the poster.
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/81f025b7-4405-4e9a-a81e-9eccc203c87e)

Interactive Test

1. Go to the figma page
2. Click on present in the top right hand corner
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/f95a0681-8f5d-4074-82f4-79f010d7bfbc)
3. Click anywhere on the event image
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/ce772e54-4eea-40ae-ab0f-5027d7268d66)
4. Verify a new screen pops up with more details on the event
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/81f025b7-4405-4e9a-a81e-9eccc203c87e)
5. Click on the 3 lines just below the event image
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/b99f39b3-4c75-43fd-ae53-449146167473)
6. Verify that you are now back on the main screen with all the events.

**Comment by junqiwu02** [comment]
Add this as a dependency to a user story

**Comment by junqiwu02** [comment]
There should be a test for interactivity as well. It should display when a user clicks a post. Work with Alex to have it display when tapping an event on the home page.

**Comment by YUBILAND** [comment]
Added interactive element so that clicking on the event will transition you to the description frame providing more detail.

**Comment by junqiwu02** [comment]
This should be a blocking dependency instead of a blocked-by dependency of the associated user story
