### ISSUE TITLE
Convert the homepage and login page into a single page, each being a single frame for seamless transition between the two frames

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#24]
*Task Tests*

test 1:
- go to the figma page at: https://www.figma.com/file/5qJUyXFUAdbtiobIQYqH20/Project-Prototype?node-id=151%3A3&t=QH31e7QFg894LkNj-0
- make sure you are under the "Website" page and there are two separate frames for the homepage and login page, such as:
![figma-homepage-and-loginpage-as-frame.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/5119a849-21b6-43da-89c1-584c38c7ac3e)

test 2:
- click on the "Homepage" frame
- click on "login button" layer
- check if the login button on the homepage is linked to the login page such as:![figma-login-button-connected-to-loginpage.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/e16490da-337a-409f-816e-a5c469a364b2)

**Comment by junqiwu02** [comment]
Add this as a dependency of a user story
