### ISSUE TITLE
as a mobile user, I want look at big UI so I can navigate the website easily

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#25]
**Acceptance Tests*

test 1:
- go to the website page: https://www.figma.com/proto/5qJUyXFUAdbtiobIQYqH20/Project-Prototype?node-id=151%3A3&scaling=scale-down&page-id=151%3A2&starting-point-node-id=151%3A3
- ensure the UI is big enough to see clearly such as: ![big-UI.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/d4dd022c-4143-42a9-bc20-6e054af3c0cd)

**Comment by junqiwu02** [comment]
Add an assignee
