### ISSUE TITLE
[Ignore, not planned] As a member who forgot my password, I want to be able to reset my password, so I can log in with a new one

### ISSUE THREAD

**Issue by johntolo** [cse442-at-ub/project_s23-cinco#30]
Test 1:
Go to login page of website
click "forgot your password?"
See that it brings to a separate screen to reset your password

**Comment by junqiwu02** [comment]
Add assignee(s) and add the link to the website to the test.

**Comment by junqiwu02** [comment]
The description of the separate screen can also be more detailed. A screenshot can help
