### ISSUE TITLE
As a prospective member, I want to go to the sign up page so that I can create a new account

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#37]
**Acceptance Tests**

test 1:
-go to sign up page:https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/signup
-ensure you see the username, email, password, confirm password, and sign up button
![snip.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/8a22a224-1df5-42f9-9049-e4700285bb9d)
test 2: ensure it takes you back to the homepage while being logged in after submitting.

**Comment by junqiwu02** [comment]
Acceptance tests should be able to run on the deployed application. A nontechnical client is not going to know how to run npm start :( Also I don't think this story is finished yet, I think it should include the state and interactivity tasks as well.
