### ISSUE TITLE
Create static React page for the signup and login pages

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#38]
*Task Tests*

in the "Sprint2-Static-Signup-Login-Page" branch in github:
test 1
-go to signup page by doing the following:
        1)in your editor of choice, go into the project folder (project_s23-cinco) and in the terminal type "npm start". This will bring up the webpage
-check that the username, email password, confirm password, and signup button are available![snip.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/8a22a224-1df5-42f9-9049-e4700285bb9d)

test 2
-go to login page by doing the following:
       1)in your editor of choice, go into the project folder (project_s23-cinco) and in the terminal type "npm start". This will bring up the webpage
-check that the username, password, and signup button are available(screenshot later)![login.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/4629c280-7f02-4248-843c-6d90c7425ca3)

test 3:
-go to login page url by doing the following:
       1)in your editor of choice, go into the project folder (project_s23-cinco) and in the terminal type "npm start". This will bring up the webpage
-this is the normal desktop view, ensure everything stays within the boundaries of the desktop.
-press f12 when in the browser to open up the developer tools. go into the different device view (ctrl + shift + M" and switch to "Mobile S - 320px" to check if all content stays within the boundaries.

**Comment by junqiwu02** [comment]
The url doesn't exist, that's correct. So use whatever development method you have at the moment to launch the page instead. All tests should be runnable in the project's current state. Also either add tests for the desktop view as well or add a line in the existing test asserting connecting from both devices and checking correctness.

**Comment by junqiwu02** [comment]
Is the first step of the test supposed to have a link? If not, remove that step. Also, it would be helpful to specify the name of the project folder (or if it's the root directory) and what branch the test should be run on unless the app in dev opens straight to the login page?
