### ISSUE TITLE
Connect database to react app.

### ISSUE THREAD

**Issue by YUBILAND** [cse442-at-ub/project_s23-cinco#39]
Test
Navigate to https://www-student.cse.buffalo.edu/tools/db/phpmyadmin
Login to your account using your UBIT and UB person number
Go to CSE442 database "cse442_2023_spring_team_b_db", select Users table
Verify you can see username and password entries in database.

Prerequisite:
If you are not on campus and under UB wifi, you have to connect through VPN to access UB servers. Download AnyConnect here 
https://www.buffalo.edu/ubit/service-guides/software/downloading/macintosh-software/managing-mac-software/anyconnect.html
and connect to vpn.buffalo.edu/UBVPN.

Test
Run Apache webserver using XAMPP. 
Go to the root directory of the demo app and run "(sudo) npm start".
You are connected! Sadly, I don't think I can print out that you actually connected because echoing anything in the php file will assume it is the post response.

**Comment by junqiwu02** [comment]
This should be a blocking dependency, not blocked by

**Comment by YUBILAND** [comment]
Created basic js for login site. Having trouble connecting to oceanus database. PTSD from sprint 1. I can access phpmyadmin but stuck on how to connect to that from react.

**Comment by junqiwu02** [comment]
Add the commands needed for hosting the local web app. Specify which username and password to type in

**Comment by YUBILAND** [comment]
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/0fbfa15e-0b2d-4bfa-8607-ba3e0ca77352)

Seems I'm being denied access. Don't know whether its because of the password I typed or I just don't have access to the mysql server.

**Comment by YUBILAND** [comment]
Sorry for the delay, I have successfully connected to the database, the problem was that I had to be on UB wifi and I typically coded at home so I had to use UB's VPN system called AnyConnect and connect to oceanus.cse.buffalo.edu through that.

**Comment by YUBILAND** [comment]
In lieu of the fact that nodejs won't be viable as the backend from Hertz, I converted the nodejs code to php and made a separate branch for it called "Sprint2-phpserver".

**Comment by junqiwu02** [comment]
add as dependency
