### ISSUE TITLE
Figma markup page for Login page and Change in Password 

### ISSUE THREAD

**Issue by vikasithsai** [cse442-at-ub/project_s23-cinco#40]
https://www.figma.com/file/ZSq11HmtHancij9UBCY93g/PROFILE-PIC?node-id=0%3A1

Acceptance Tests

Test 1

Login into the account 
Go to settings 
Click on the change password
Enter the current password in order to verify 
Type the new password 
Type Again 
Password Changed!!!

**Comment by junqiwu02** [comment]
Add this as a dependency of a user story. Also, I think the test is incorrect, are you actually able to do all that with a Figma?

**Comment by junqiwu02** [comment]
The test is incorrect. You cannot perform these actions on a wireframe. The test should just be opening the wireframe and an assertion that the page is displayed correctly.
Also all tasks need to be a blocking dependency of a user story. Please fix this.
