### ISSUE TITLE
Figma Markup for changing the password 

### ISSUE THREAD

**Issue by vikasithsai** [cse442-at-ub/project_s23-cinco#42]
https://www.figma.com/file/ZSq11HmtHancij9UBCY93g/PROFILE-PIC?node-id=0%3A1

Test 1:
Click on the above link in order to view figma markup page for changing password.

![Image 01-04-23 at 5.00 PM.jpg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/8bf78839-a6ff-4d94-baa4-99e26f660d00)

**Comment by junqiwu02** [comment]
Add tests and make this a dependency of a user story

**Comment by junqiwu02** [comment]
The tests need to be runnable. Can you actually log in and change the password using the Figma? If not, it should reflect the static nature of the wireframe.

**Comment by junqiwu02** [comment]
Also if this is a task, it should not have the user story tag

**Comment by junqiwu02** [comment]
The test is incorrect. You cannot perform these actions on a wireframe. The test should just be opening the wireframe and an assertion that the page is displayed correctly.
