### ISSUE TITLE
Create static components for changing profile picture and password

### ISSUE THREAD

**Issue by vikasithsai** [cse442-at-ub/project_s23-cinco#43]
Task Tests

Test 1:

Run the tests in dev branch
Enter the command "npm start" in terminal 
It opens the local host
Verify the page looks like the screenshot

![Image 09-03-23 at 11.13 AM.jpg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/da9c7021-bfe6-4c9d-abdc-8a9c891009ee)

**Comment by junqiwu02** [comment]
The title should follow the format: "As a [role], I want [action taken] so that [observable outcome]"

**Comment by junqiwu02** [comment]
The title is still not following the format. Also the description of the user needs to be more specific, not just a "member"

**Comment by junqiwu02** [comment]
The tests need to be fixed per my comment in #48, or just have the test be something like "Run the task test in #48"

**Comment by junqiwu02** [comment]
You did not fix the issue, please see my previous comments.

**Comment by junqiwu02** [comment]
tasks need to be a blocking dependency
