### ISSUE TITLE
As a member who wants to know my credentials, I want to go to my profile so I can see all my credentials in one place

### ISSUE THREAD

**Issue by johntolo** [cse442-at-ub/project_s23-cinco#45]
Test 1:
go to url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
Click on profile
Ensure that it takes you to the profile page and shows your name, username, website, bio, and email. These entries should be text boxes that will have your information already in them

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/efef7d45-62d0-4b4d-afef-edd10f1e653e)

**Comment by junqiwu02** [comment]
Add the appropriate assignees

**Comment by junqiwu02** [comment]
The description of the page in the test needs to be more detailed. Either add a more detailed description of the layout or add a screenshot

**Comment by junqiwu02** [comment]
The description of the user needs to be more detailed. "As a member" is not sufficient.

**Comment by junqiwu02** [comment]
Add sprint labels

**Comment by junqiwu02** [comment]
add a link and screenshot to the test

**Comment by junqiwu02** [comment]
make sure the all tests are run before moving to completed
