### ISSUE TITLE
Create static react page for the profile page

### ISSUE THREAD

**Issue by johntolo** [cse442-at-ub/project_s23-cinco#46]
Test 1:
run npm start
Go to profile page url: http://localhost:3000/edit-profile
Ensure that there is the pfp, edit pfp, name, username, website, bio, and email

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/b5d2da98-87b8-4a7b-9b41-6c3b4bfc7d16)

**Comment by junqiwu02** [comment]
The test needs the url for the profile page

**Comment by junqiwu02** [comment]
Add this as a dependency of a user story

**Comment by junqiwu02** [comment]
If the website is running on localhost, you need to specify how to launch it as well. I.e. run "npm start" or whatever command you're using
