### ISSUE TITLE
As a member who want to change the password and change the profile picture, I want to utilise the action of buttons so that change the password and profile picture 

### ISSUE THREAD

**Issue by vikasithsai** [cse442-at-ub/project_s23-cinco#48]
Acceptance Test 
Test 1: 

A static page with the option to display "Change password" and  "Change profile picture". 
Though it's a static page with no functionality the keys doesn't work. Also it's on running on the local host

![image.png](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/e8371f16-e2e1-420b-8a7b-be7385285a7b)

**Comment by junqiwu02** [comment]
Add as a dependency of a user story. And I think the tests are incorrect. Are you actually able to change the profile picture and password from a static site?

**Comment by junqiwu02** [comment]
Please change the tests per my previous comment. Also this should be _blocker_ dependency, not a _blocked by_. Also, tasks should not be a dependency of another task

**Comment by junqiwu02** [comment]
Tasks should be a _blocking_ dependency not a _blocked by_. Please fix this. Also the tests are incorrect, those are not runnable. A test for the static page should just include the link or method to open the page and an assertion that the page is displayed correctly (on both mobile and desktop views)
