### ISSUE TITLE
as a browser, I want to click on the login and signup buttons to direct me to the respective pages.

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#49]
**Acceptance Tests**

test 1:
-go to the homepage at: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/.
- click on the login button and ensure it takes you to the login page

test 2:
-go to the homepage at: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/.
- click on the signup button and ensure it takes you to the signup page

**Comment by junqiwu02** [comment]
Acceptance tests should be able to run on the deployed application. A nontechnical client is not going to know how to run npm start :(

**Comment by junqiwu02** [comment]
Change npm start to the actual link

**Comment by junqiwu02** [comment]
cheshire link
