### ISSUE TITLE
As a member who's interested in editing my account, I want to go to the settings page so I can see tabs for editing my profile and my account settings

### ISSUE THREAD

**Issue by johntolo** [cse442-at-ub/project_s23-cinco#52]
Test 1:
Go to settings page
See that there are tabs for editing the profile and account settings
Confirm that clicking each tab brings you to the respective page

The profile settings will look like this:![Screenshot (1019).png](https://images.zenhubusercontent.com/63e2cfbfaca3b22752e618ee/722ec6a8-8cfd-49ca-893a-674bc1671a7a)![Screenshot (1020).png](https://images.zenhubusercontent.com/63e2cfbfaca3b22752e618ee/7ae5fb5f-a75d-492e-a753-7c1d6b7329b2)

**Comment by junqiwu02** [comment]
add assignee
