### ISSUE TITLE
Modify profile page into a settings page with tabs for editing the profile and account settings

### ISSUE THREAD

**Issue by johntolo** [cse442-at-ub/project_s23-cinco#53]
Test 1:
Go to edit profile url: http://localhost:3000/edit-profile
Ensure that it says "Settings" in the header
Check that clicking on the tabs for "Edit Profile" and "Account Settings" brings you to the respective pages

**Comment by junqiwu02** [comment]
Missing url and add screenshots

**Comment by junqiwu02** [comment]
say to run npm start
