### ISSUE TITLE
As a member who want to login and logout, I want to utilise the action of buttons so that login and logout keys can be used

### ISSUE THREAD

**Issue by vikasithsai** [cse442-at-ub/project_s23-cinco#54]
Acceptance Test
Test 1:

A static page with the option to display "login" and  "logout".
Though it's a static page with no functionality the keys doesn't work. Also it's on running on the local host

**Comment by junqiwu02** [comment]
Make the description of the user more detailed. "Member" is not detailed enough

**Comment by junqiwu02** [comment]
The user description still needs to be more detailed. It cannot be simply "as a user".

**Comment by junqiwu02** [comment]
add dependency and sprint label
