### ISSUE TITLE
Add routing to profile, account settings, and login button on navbar

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#58]
*Task Tests*

run in "Sprint2-Navbar-Buttons" branch in github

test1:
- in the project folder (project_s23-cinco) run "npm start" in the terminal, this will open the homepage in a browser
- look at the navbar and ensure it has the following buttons: "profile", "account settings", "login"![navbar-profile-account-login.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/5e880ed6-8151-4e1e-927d-96291bebd670)

-in a mobile view, click on the burger icon to ensure the following buttons are included: "profile, "login", "account settings":![mobile-view-buttons.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/42f79de8-067e-40d8-9c6e-3eb45821762a)

-click on "profile" to get to edit profile page:![edit-profile-img.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/8e5f5415-76d1-4978-b4ec-302f1e0c321d)
-click on "account settings" to get to the account settings page:![account-settings-page.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/a571095f-bd0c-4000-b3b8-5ed690986f0d)
-click on "login" to get to login page:![login-page.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/ce877b30-5cea-4497-8a58-de3c627995b8)

**Comment by junqiwu02** [comment]
add as dependency

**Comment by junqiwu02** [comment]
add test for mobile version
