### ISSUE TITLE
Implement php password hashing

### ISSUE THREAD

**Issue by YUBILAND** [cse442-at-ub/project_s23-cinco#62]
Go to current build https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build-hashpass
Click on Login, then Sign Up
Enter in any valid credential you like (fill in all fields and make sure passwords match) and hit register
Navigate to database by going to https://www-student.cse.buffalo.edu/tools/db/phpmyadmin -> users table.
Verify that your entry's password (at the bottom) is not being stored as plain text.
Try copying the hashed password in the database and entering it in the login screen.
Verify you cannot login by the error indicating wrong credentials.
Now enter in the credentials you used to login.
Verify you can login by being redirected to the event page.

**Comment by junqiwu02** [comment]
add dependency
