### ISSUE TITLE
as a user who wants to update my settings, I want to change my profile settings so I  see the new updated credentials on the page

### ISSUE THREAD

**Issue by johntolo** [cse442-at-ub/project_s23-cinco#66]
Test 1:
go to url https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
click login
login with credentials
Go to Profile and update your settings and click save changes
Go back to home page then go back and ensure the updated settings are autofilled in the text boxes

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/a5b97c03-a187-47aa-9b97-fb29a4ec1f1c)

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/0e5e78b1-35f2-4317-9350-e51236059910)

**Comment by junqiwu02** [comment]
add link and screenshots
