### ISSUE TITLE
as a browser looking at different events, I want to click on an event to see more information about it

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#67]
**Acceptance tests**

*test1
- go to website url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build
- click on an event thumbnail
- ensure the event popup displays![event-popup-comments.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/28f10c5f-5bbf-4147-8412-f9a450f13b01)

Test 2 
-do steps 1,2 for test1
-check the description to learn about the event and location
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/a2e53992-d70d-4cd1-b5ce-ecd67c2f0bb2)

**Comment by junqiwu02** [comment]
make desc of user more detailed

**Comment by junqiwu02** [comment]
update the popup with the latest version
