### ISSUE TITLE
Create static components for login and logout page.

### ISSUE THREAD

**Issue by vikasithsai** [cse442-at-ub/project_s23-cinco#70]
Task Tests

Test 1:

Run the tests in dev branch
Enter the command "npm start" in terminal
It opens the local host
Verify the page looks like the screenshot

![863bfcc6-45ee-42c9-9453-ab6f13f8c6b3.jpg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/6dbc6bd2-24aa-44ab-b0cb-fef9961adf8d)![23d1d587-59e4-4658-b9e4-56e0b4f1ac65.jpg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/a146fb40-8425-4183-b184-bcf6f919d429)

**Comment by junqiwu02** [comment]
tasks need to be a blocking dependency
