### ISSUE TITLE
As a logged in member worried about security, I want to click the sign out button so that I sign out of my account

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#71]
**Acceptance tests**

-go to website url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
-click sign up and sign up with a new account
-log in to the newly created account, the homepage should show profile, account settings, etc.:![logged-in.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/8bf574de-08c7-4aea-84c2-e2eaed002813)

-in the homepage, click the sign out button. 
-ensure a login button appears, indicating you were signed out.:
![not-logged-in.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/41d8541a-6a44-4d7a-a76a-99c3ffdd711b)

**Comment by junqiwu02** [comment]
Make the description of the user more detailed in the title

**Comment by junqiwu02** [comment]
The test should be runnable by a non-technical user. A non-technical user should not be expected to be able to use the dev tools in chrome

**Comment by junqiwu02** [comment]
the title is missing a "so that [outcome]"

**Comment by junqiwu02** [comment]
add screenshots
