### ISSUE TITLE
Create Static react components for edit and delete

### ISSUE THREAD

**Issue by vikasithsai** [cse442-at-ub/project_s23-cinco#73]
Task Tests

Test 1:

Run the tests in dev branch
Enter the command "npm start" in terminal
It opens the local host
Verify the page looks like the screenshot

![cc5c4eb2-f0eb-4f0a-b4d1-fafc8a5a6d9b.jpg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/e1405f30-f023-4627-bdcb-9b37f0d02f3d)

![86b949ba-867d-4202-9218-e3bc385d43eb.jpg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/e6ab1d62-d010-44b5-af83-370499bdd5c0)

**Comment by junqiwu02** [comment]
tasks must be a _blocking_ dependency. *Please see this in the style guide*
