### ISSUE TITLE
Connect Create Event to Backend

### ISSUE THREAD

**Issue by tyland5** [cse442-at-ub/project_s23-cinco#75]
**Task Tests**

*Test 1*
Checking for successful image uploads
1) Visit https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/create-event
    If prompted to log in, log in
2) Fill out the create event form. Preferably with multiple images uploaded in event images
3) Check out the webserver and see if the files are properly uploaded. Should be post{id}_thumbnail and all the images as post{id}_img{number}![Screenshot (1053).png](https://images.zenhubusercontent.com/63e2cfbfaca3b22752e618ee/b1150270-384f-47a4-987d-0fa1323768b2)
4) Check out data base too if you want and check for similarities in content![Screenshot (1055).png](https://images.zenhubusercontent.com/63e2cfbfaca3b22752e618ee/f88700d8-ffce-4813-8aee-894467972941)

*Test 2*
Checking for sanitizing content
1) Visit https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/create-event
    If prompted to log in, log in
2) Fill out the create event form, but with html tags and stuff in the input 
3) Check the database, should look like post id 1's title![Screenshot (1055).png](https://images.zenhubusercontent.com/63e2cfbfaca3b22752e618ee/f5141cfa-3864-4ef2-831e-f3074b4fd02e)

**Comment by tyland5** [comment]
Spent a couple hours finishing connecting all fields to the backend properly except for event images. Still struggling on that

**Comment by junqiwu02** [comment]
add dependency
