### ISSUE TITLE
Retrieve and load events from database to feed

### ISSUE THREAD

**Issue by YUBILAND** [cse442-at-ub/project_s23-cinco#76]
Task Tests

Test 1: 
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build
2. Verify you can see events that are different and unique.
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/d510fd3b-f0cc-4a70-b311-cae96283266c)
3. Click on an event and verify you can see the post info such as poster, description, thumbnail, image, etc.
4. Go to the database -> Posts https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/sql.php?server=1&db=cse442_2023_spring_team_b_db&table=Posts&pos=0
and verify that you can see the thumbnail image name corresponding to the poster.
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/f6b9e06c-9b00-4161-82cd-7439ce75b4c4)
6. Access the directory within the cheshire server via WinSCP or CyberDuck
7. Go into the uploads folder and make sure you can see the exact file name in the folder.
![image.png](https://images.zenhubusercontent.com/63e2cfc50476ff4c250db692/1415761e-4665-495d-899f-a20af8636389)
8. Download it to make sure it is the exact same image.

**Comment by YUBILAND** [comment]
Events in db displaying correctly. Haven't incorporated imgs or thumbnails yet.

**Comment by junqiwu02** [comment]
expand on the db verifcation

**Comment by YUBILAND** [comment]
Explained that to verify you should look at the db and the cheshire web server
