### ISSUE TITLE
Add static like, dislike, comment, a share button and a feature to exit the event popup display by clicking away from the event popup.

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#78]
*Task Tests*

test 1:
1) go to website on desktop: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2) click on an event thumbnail to open event popup view
3) ensure the like, dislike, comment, and share button are displayed on the bottom of the event view:![event-popup-comments.PNG](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/6d8bbe51-7185-4492-a4e3-7178388c0574)

test2:
1) go to website on mobile: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2) click on an event thumbnail to open event popup view
3) ensure the like, dislike, comment, and share button are displayed on the bottom of the event view:
![Screenshot_20230408_210408_Chrome.jpg](https://images.zenhubusercontent.com/63e2d05608ee4c45e81f66f0/73e281c2-1058-4f69-9856-741162744e64)
test3:
1)go to website: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2)click on the thumbnail of an event
3)ensure the event popup displayed
4)click on the darkened area outside of the event popup view
5)ensure the event popup closed

**Comment by junqiwu02** [comment]
add pfp, username, and timestamp to the comments
