### ISSUE TITLE
Make navbar stateful

### ISSUE THREAD

**Issue by johntolo** [cse442-at-ub/project_s23-cinco#79]
Test 1:
Go to website: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build
Once on website, ensure that user-specific pages are not on navbar (Profile, settings, sign out).
click login and login with username: host, password: 123.
Ensure that user-specific pages are now visible, login and sign up tabs are not on navbar

Test 2:
Go to website: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build
Login with same credentials as Test 1.
Click "Sign Out"
Ensure that you are taken back to the home page and the navbar reverts back to what it was before logging in (see screenshot)

Test 3:
Go to website: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build
Login with same credentials as Test 1.
go to the mobile view in inspect and click the hamburger menu in the top left.
Ensure that user-specific pages are now visible, login and sign up tabs are not in menu (see screenshot)

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/41de4a01-2a65-42a0-947a-2ec4c9b6b8e4)

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/02c5ea92-8c8d-4795-bdc7-647db86991ba)

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/3355fe39-b4e4-4f10-b6e0-fecb218ade98)

![image.png](https://images.zenhubusercontent.com/63e2cf463bc662d519ec1cc1/4e7ab331-9497-4a2b-a7b2-46d7bec2d525)

**Comment by junqiwu02** [comment]
add dependency

**Comment by junqiwu02** [comment]
add some screenshots to the tests
