### ISSUE TITLE
As a member who want to edit and delete, I want to go to my site so that I can use the features of the interface including edit and delete

### ISSUE THREAD

**Issue by vikasithsai** [cse442-at-ub/project_s23-cinco#82]
Acceptance Test 

Test 1:

Enter the command " https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/ "

Verify the page looks like the screenshot

![2ABD070D-5520-4C2A-9A7A-2D011F9A07D9.jpeg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/4e192317-52d5-4a45-82de-6deafcd4e1ce)

Click on manage events 
"Edit" and "Delete" integrated with the event management page
Though it's a static page with no functionality the keys doesn't work. 

![A66EC6E2-AA3E-4F51-8398-D83EA9D82F11.jpeg](https://images.zenhubusercontent.com/63e2d168e959fbd010460226/0be5a95f-4d78-4458-9fdf-97851d25cf61)

**Comment by junqiwu02** [comment]
Tests need to be imperative or assert something, they cannot be simply declarative.

**Comment by junqiwu02** [comment]
insert link to cheshire, acceptance tests cannot be run using npm start
