### ISSUE TITLE
Create mini tutorial document for Figma

### ISSUE THREAD

**Issue by tyland5** [cse442-at-ub/project_s23-cinco#9]
**Task Tests**

*Test 1*
1) Go to https://docs.google.com/document/d/1fsVB6Wnu_IjQBG7xagPBVb3xZiERE08UYkERNkZXSgc/edit?usp=sharing
1) Assure that the information included in the document can help guide you to make a basic example page
2) Verify that all the videos included in the document have explanations of why they were included and what they are about

**Comment by junqiwu02** [comment]
Make sure the tests are actual things to perform to ensure the task was completed without bugs. Step 2 in test 1 is more of a requirement.

**Comment by junqiwu02** [comment]
![image](https://user-images.githubusercontent.com/22561215/219899546-245c3c04-e7e7-4b46-9bb3-567b1b0e0535.png)
This is an example image
