### ISSUE TITLE
Make like/dislike button clicked only once by user and only one of them can be selected 

### ISSUE THREAD

**Issue by Fivea5** [cse442-at-ub/project_s23-cinco#95]
**Task Tests**

test 1:
1.go to website url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2.click the log in button to log in if you are not logged in
3.click on an event thumbnail to open the event popup
4.click the like button 2 times to ensure the counter only went up by 1.

test 2:
1.go to website url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2.click the log in button to log in if you are not logged in
3.click on an event thumbnail to open the event popup
4.click the like button, ensure it went up by 1, then click the dislike button and ensure that number didn't change

test 3:
1. go to website url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2. click the log in button to log in if you are not logged in
3.click on an event thumbnail to open the event popup
4.click on the like button and ensure the counter went up by 1
5.click on the dislike button and ensure the counter didn't go up or down.
6.click on the like button again and ensure the counter went down by 1
7.click on the dislike button and ensure the counter went up by 1

test 4:
1. go to website url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2. click the log in button to log in if you are not logged in
3.click on an event thumbnail to open the event popup
4.click on the dislike button and ensure the counter went up by 1
5.click on the like button and ensure the counter didn't go up or down.
6.click on the dislike button again and ensure the counter went down by 1
7.click on the like button and ensure the counter went up by 1

test 5:
1. go to website url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2. click on sign out if you are logged in, if not then continue
3.click on an event thumbnail to open the event popup
4.click on the dislike button and ensure you are redirected to the login page

test 6:
1. go to website url: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2. click on sign out if you are logged in, if not then continue
3.click on an event thumbnail to open the event popup
4.click on the like button and ensure you are redirected to the login page

**Comment by junqiwu02** [comment]
add a test for if the user is logged out
