### ISSUE TITLE
Create event code feature 

### ISSUE THREAD

**Issue by tyland5** [cse442-at-ub/project_s23-cinco#96]
**Task Tests**

*Test 1*
1) Go to the website and login: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2) Click on a post, click on the far most left button (to the left of the comment button), and enter the correct event code into the text input. It'll look like this:![Screenshot (66).png](https://images.zenhubusercontent.com/63e2cfbfaca3b22752e618ee/1f42f007-859c-412c-80d6-42a1ec95ff5e)

3) Check if the User Attendance row for the specific user_id you're logged in gets correctly incremented in the total events and the corresponding event type columns.
4) Try inputting the same code again. It will give you a message saying you were already marked as attended. The data table will not increment. Click on close to close the prompt

*Test 2*
1) Go to the website and and create a new account: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2) Check if a new row is made in the User Attendance table
3) Do steps 2-4 in Test 1

*Test 3*
1) Go to the website, login: 1) Go to the website and login: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442b/build/
2) make a new post. set the event code to something you'll remember like 'apple'
3) do steps 2-4 in test 1

**Comment by junqiwu02** [comment]
add a dependency
